#!/usr/bin/env bash

# this script is for setting up symbolic links to the dotfiles


### bashrc loading 
BASHFILE=$HOME/.bashrc
if [ ! -L "${BASHFILE}" ]; then
	# if regular file exists delete and symlink
	ln -nsf $HOME/dotfiles/.bashrc "${BASHFILE}"
elif [ ! -e "${BASHFILE}" ]; then
	# if file does not exist just create symlink
	ln -s $HOME/dotfiles/.bashrc "${BASHFILE}"
fi
# reload bashfile
source "${BASHFILE}"

### vimrc loading
VIMFILE=$HOME/.vimrc
if [ ! -L "${VIMFILE}" ]; then
	# if regular file exists delete and symlink
	ln -nsf $HOME/dotfiles/.vimrc "${VIMFILE}"
elif [ ! -e "${VIMFILE}" ]; then
	ln -s $HOME/dotfiles/.vimrc "${VIMFILE}"
fi

### package loading

pkgs=( 'wget'  'screen' 'vim' )
sudo apt update
sudo apt install -y --ignore-missing "${pkgs[@]}"


